#**1️⃣ Load the Data**

In [9]:
import pandas as pd

# Load the dataset
train_path = "/content/drive/MyDrive/Credit Card Transactions Fraud Detection/fraudTrain.csv"  # Update with the correct path
test_path = "/content/drive/MyDrive/Credit Card Transactions Fraud Detection/fraudTest.csv" # Update with the correct path

df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

# Display basic information about the dataset
print(df_train.info())
df_train.head()  # View first few rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB
None

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [10]:
print(df_test.info())
df_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB
None

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

#**2️⃣ Preprocess Data**

###**Handle Date/Time Features**

In [11]:
# Check for missing values
print(df_train.isnull().sum())
print(df_test.isnull().sum())

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64
Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

###**Handle Age Feature**

In [12]:
# Convert transaction timestamp to datetime format
df_train['trans_date_trans_time'] = pd.to_datetime(df_train['trans_date_trans_time'])
df_test['trans_date_trans_time'] = pd.to_datetime(df_test['trans_date_trans_time'])

# Extract relevant time-based features
for df in [df_train, df_test]:
    df['hour'] = df['trans_date_trans_time'].dt.hour
    df['day'] = df['trans_date_trans_time'].dt.day
    df['month'] = df['trans_date_trans_time'].dt.month
    df['year'] = df['trans_date_trans_time'].dt.year

In [13]:
from datetime import datetime

# Convert 'dob' to age
def calculate_age(dob):
    today = datetime.today()
    birth_date = datetime.strptime(dob, "%Y-%m-%d")
    return today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))

df_train['age'] = df_train['dob'].apply(calculate_age)
df_test['age'] = df_test['dob'].apply(calculate_age)

#**3️⃣ Encode Categorical Variables**

In [14]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['category', 'gender', 'job', 'state']

encoders = {}  # Dictionary to store encoders for each column

for col in categorical_cols:
    encoders[col] = LabelEncoder()

    # Fit on training data
    df_train[col] = encoders[col].fit_transform(df_train[col])

    # Transform test data (handle unseen categories)
    df_test[col] = df_test[col].apply(lambda x: encoders[col].transform([x])[0] if x in encoders[col].classes_ else -1)

#**4️⃣ Select Features for Model Training**

In [15]:
# Define features to use
features = ['amt', 'hour', 'day', 'month', 'year', 'category', 'lat', 'long', 'city_pop', 'job', 'age']
target = 'is_fraud'

# Prepare training and test data
X_train, y_train = df_train[features], df_train[target]
X_test, y_test = df_test[features], df_test[target]

#**5️⃣ Train a Machine Learning Model**

In [18]:
from re import VERBOSE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Split training data into train/validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Train Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate on validation set
y_val_pred = model.predict(X_val)
print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print(confusion_matrix(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred))

Validation Accuracy: 0.9984093932558274
[[206197     36]
 [   294    941]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    206233
           1       0.96      0.76      0.85      1235

    accuracy                           1.00    207468
   macro avg       0.98      0.88      0.93    207468
weighted avg       1.00      1.00      1.00    207468

#**6️⃣ Test Model on Unseen Data**

In [19]:
# Predict on test data
y_test_pred = model.predict(X_test)

# Evaluate model performance
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

Test Accuracy: 0.9986809880533147
[[553486     88]
 [   645   1500]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.94      0.70      0.80      2145

    accuracy                           1.00    555719
   macro avg       0.97      0.85      0.90    555719
weighted avg       1.00      1.00      1.00    555719

#**7️⃣ Analyze Misclassifications**

In [20]:
df_test['predicted'] = y_test_pred
df_test['actual'] = y_test

# Find misclassified transactions
misclassified = df_test[df_test['predicted'] != df_test['actual']]
print("Misclassified Transactions:\n", misclassified.head())

Misclassified Transactions:
       Unnamed: 0 trans_date_trans_time            cc_num  \
1685        1685   2020-06-21 22:06:39  3560725013359375
1695        1695   2020-06-21 22:09:41     4427805710168
1891        1891   2020-06-21 23:16:12  3524574586339330
2173        2173   2020-06-22 01:18:02  3524574586339330
2495        2495   2020-06-22 03:48:20  3524574586339330

                         merchant  category     amt     first       last  \
1685         fraud_Hamill-D'Amore         5   24.84    Brooke      Smith
1695       fraud_Lebsack and Sons         8  890.22  Michelle  Rodriguez
1891       fraud_Thompson-Gleason         5   22.55    Ashley    Cabrera
2173  fraud_Yost, Block and Koepp         9    8.39    Ashley    Cabrera
2495       fraud_Skiles-Ankunding         3   13.25    Ashley    Cabrera

      gender                         street  ...  merch_lat  merch_long  \
1685       0      63542 Luna Brook Apt. 012  ...  32.575873 -102.604290
1695       0  1742 Brandon Squares Apt. 461  ...  34.154798 -106.551531
1891       0   94225 Smith Springs Apt. 617  ...  28.396402  -80.819469
2173       0   94225 Smith Springs Apt. 617  ...  27.059901  -80.323830
2495       0   94225 Smith Springs Apt. 617  ...  27.874482  -80.381534

      is_fraud  hour  day  month  year age predicted  actual
1685         1    22   21      6  2020  55         0       1
1695         0    22   21      6  2020  24         1       0
1891         1    23   21      6  2020  38         0       1
2173         1     1   22      6  2020  38         0       1
2495         1     3   22      6  2020  38         0       1

[5 rows x 30 columns]

#**8️⃣ Save the Model**

In [21]:
import joblib

# Save trained model
joblib.dump(model, '/content/drive/MyDrive/Credit Card Transactions Fraud Detection/fraud_detection_model.pkl')

['/content/drive/MyDrive/Credit Card Transactions Fraud Detection/fraud_detection_model.pkl']